name: medicare
description: Doctor Appointment App
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  flutter_map:
  get:
  cached_network_image: ^3.2.0
  intl:
  firebase_auth:
  firebase_core:
  flutter_svg:
  cloud_firestore:
  cool_alert:
  marquee:
  firebase_storage:
  firebase_analytics:
  image_picker:
  path:
  dropdown_plus:
  date_time_picker:
  video_player:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  enabled: true
